halobject: close the eventloop after it is stopped
Halibot/halibot pull request #81
Opened 2017-09-14 16:10 UTC by richteer

This suppresses a nondeterministic exception thrown from the tests when
the bot shuts down too quickly. Probably exists with regular closing
too.

This PR is mostly to see if it magically fixes our non-deterministic travis builds

2017-09-14 17:57 UTC, richteer commented
This implements issue #66 , though it does continue to not answer the question of handling restarts.

2017-09-15 15:29 UTC, sjrct commented
This could cause us to lose events if it is called before `eventloop.stop` is called. I agree we need to call `eventloop.close`, but not here. As `stop` causes `run_forever` to exit, it should probably be called immediately after the `run_forever` loop is exited. This can be accomplished by creating a new function that just runs the event loop forever and then closes the event loop, making this the target of the event loop thread.

Eg:
```python
class HalObject():

  def __init__(self, hal, conf={}):
    # ...
    self._thread = Thread(target=self.run_eventloop)
    self._thread.start()

  def run_eventloop(self):
    self.eventloop.run_forever()
    self.eventloop.close()

  # ...
```

2017-09-15 15:32 UTC, sjrct requested changes
This could cause us to lose events if it is called before `eventloop.stop` is called. I agree we need to call `eventloop.close`, but not here. As `stop` causes `run_forever` to exit, it should probably be called immediately after the `run_forever` loop is exited. This can be accomplished by creating a new function that just runs the event loop forever and then closes the event loop, making this the target of the event loop thread.

Eg:
```python
class HalObject():

  def __init__(self, hal, conf={}):
    # ...
    self._thread = Thread(target=self.run_eventloop)
    self._thread.start()

  def run_eventloop(self):
    self.eventloop.run_forever()
    self.eventloop.close()

  # ...
```

2017-09-15 15:34 UTC, richteer commented
Hmmm... this implies that every time we stop the eventloop, it will always close it too. Is that an acceptable side effect? I think it is fine, not sure how many use cases there ever will be for stopping an eventloop with the intent of starting it again.

2017-09-15 17:33 UTC, sjrct approved these changes

2017-09-15 17:34 UTC, merged