Add a config writing method to Halibot core
Halibot/halibot pull request #96
Opened 2017-10-21 16:13 UTC by richteer

In `main.py`, we use the `Halibot` class to load the config, so we might as well write the config using it as well. We should probably consider a kwarg to `Halibot` for `config_path`, so we can stop hardcoding `"config.json"` everywhere -- it can be a command line argument if people really want to change it. Or if we decide that it should be `"halibot.json"` (which I'm starting to think might be better for clarity), it would be easier to fix everywhere.

2017-10-21 16:23 UTC, richteer commented
I can code good. Fixed my stupid bugs from before, tests now pass.

2017-10-21 16:28 UTC, richteer commented
Okay, I think I actually fixed the stupid bugs this time. I no code good.

2017-10-22 05:57 UTC, sjrct requested changes
Missed writing the config again at `main.py#43`. Might want to be able to take a file path as an argument to accommodate this line, or maybe make an active directory a field of the `Halibot` object and have it load/write the config from there. I favor the second approach myself.

I also think we should remove the check for the config's existence at `main.py#59`. Probably would be better to fail in `_load_config`. And with the second approach to the config location from above, we do not have to worry about this getting off kilter when running with a non-local config.

2017-10-22 05:57 UTC, sjrct commented on halibot/halibot.py
> +
Extra newline.

2017-10-22 07:06 UTC, richteer commented
> Missed writing the config again at main.py#43

Yeah, I was purposely ignoring those since they were effectively dumping a new file, rather than writing a `Halibot` instance's config. I agree the "active directory" field is probably the better approach in general. 

What are your thoughts on implementation? Default value to `"."`? kwarg on `__init__()`? Or just a straight field that can be modified? Personally, I'm partial to putting it on init, with a default of `"."`.

2017-10-23 14:09 UTC, sjrct commented
I agree main.py is not something to worry about too much. I am also partial to `__init__(..., working_directory=".")` or something like that.

2017-10-25 00:48 UTC, sjrct approved these changes

2017-10-25 00:51 UTC, sjrct approved these changes

2017-10-25 00:51 UTC, merged